// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagonIVFBOymj6KNspNjIcn4I1YNOObNU',
    appId: '1:51381034534:web:21e1530f4ceabc950410e7',
    messagingSenderId: '51381034534',
    projectId: 'agrishade-428de',
    authDomain: 'agrishade-428de.firebaseapp.com',
    storageBucket: 'agrishade-428de.firebasestorage.app',
    measurementId: 'G-CMLH28WQC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMavdlLaJCnAImDKQ6abMQrqatFIud1_Y',
    appId: '1:51381034534:android:7bf35078555903aa0410e7',
    messagingSenderId: '51381034534',
    projectId: 'agrishade-428de',
    storageBucket: 'agrishade-428de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuIEVOaNTw_IFxiCvjW1voAcyadljP5E',
    appId: '1:51381034534:ios:92a9b10716bddcc80410e7',
    messagingSenderId: '51381034534',
    projectId: 'agrishade-428de',
    storageBucket: 'agrishade-428de.firebasestorage.app',
    iosBundleId: 'com.example.agrishade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChuIEVOaNTw_IFxiCvjW1voAcyadljP5E',
    appId: '1:51381034534:ios:92a9b10716bddcc80410e7',
    messagingSenderId: '51381034534',
    projectId: 'agrishade-428de',
    storageBucket: 'agrishade-428de.firebasestorage.app',
    iosBundleId: 'com.example.agrishade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAagonIVFBOymj6KNspNjIcn4I1YNOObNU',
    appId: '1:51381034534:web:70f08449ac8473c30410e7',
    messagingSenderId: '51381034534',
    projectId: 'agrishade-428de',
    authDomain: 'agrishade-428de.firebaseapp.com',
    storageBucket: 'agrishade-428de.firebasestorage.app',
    measurementId: 'G-G41NKV6BDQ',
  );
}
